openapi: 3.0.3 # [必須] OpenAPIのバージョン
info: # [必須] APIの基本情報
  title: articlets # APIのタイトル
  version: 1.0.0
  description: 記事の一覧を取得するAPI

servers: # APIサーバーのURL
  - url: https://api.example.com/v1
paths: # 「必須」エンドポイント（URLパス）の定義
  /articles: # パス
    get: # HTTPメソッド
      summary: DBのarticlesテーブルから記事の一覧を取得する
      responses: # レスポンスの定義
        "200":
          description: 記事一覧の取得に成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
